<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ValenceControl.Api\ValenceControl.Api.csproj" />
    <ProjectReference Include="..\..\src\ValenceControl.PackageCatalog.Core\ValenceControl.PackageCatalog.Core.csproj" />
    <ProjectReference Include="..\..\src\ValenceControl.Studio.Submit\ValenceControl.Studio.Submit.csproj" />
    <ProjectReference Include="..\..\src\ValenceControl.Workflows.RuntimeApplier\ValenceControl.Workflows.RuntimeApplier.csproj" />
    <ProjectReference Include="..\ValenceControl.PackageCatalog.Testing\ValenceControl.PackageCatalog.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
