<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\ElsaControl.Deployment.Abstractions\ElsaControl.Deployment.Abstractions.csproj" />
    <ProjectReference Include="..\ElsaControl.Deployment.Artifacts\ElsaControl.Deployment.Artifacts.csproj" />
    <ProjectReference Include="..\..\RuntimeBuilder\ElsaControl.RuntimeBuilder.Abstractions\ElsaControl.RuntimeBuilder.Abstractions.csproj" />
  </ItemGroup>
</Project>
