<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ElsaControl.Deployment.Proof\ElsaControl.Deployment.Proof.csproj" />
    <ProjectReference Include="..\ElsaControl.Deployment.Azure\ElsaControl.Deployment.Azure.csproj" />
  </ItemGroup>
</Project>
