<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\PackageCatalog\ValenceControl.PackageCatalog.Core\ValenceControl.PackageCatalog.Core.csproj" />
    <ProjectReference Include="..\..\..\src\RuntimeBuilder\ValenceControl.RuntimeBuilder.Abstractions\ValenceControl.RuntimeBuilder.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\src\RuntimeBuilder\ValenceControl.RuntimeBuilder.Core\ValenceControl.RuntimeBuilder.Core.csproj" />
    <ProjectReference Include="..\..\..\src\RuntimeBuilder\ValenceControl.RuntimeBuilder.DeploymentTemplates\ValenceControl.RuntimeBuilder.DeploymentTemplates.csproj" />
    <ProjectReference Include="..\..\PackageCatalog\ValenceControl.PackageCatalog.Testing\ValenceControl.PackageCatalog.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
