using System.Text;

namespace Elsa.Platform.PackageCatalog.Core.Builder.Renderers;

public sealed class ProgramReferenceBundleRenderer : IBundleFileRenderer
{
    public int Order => 60;

    public BundleFile Render(BundleGenerationContext context, List<BundleFinding> findings)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// Optional reference output generated by Elsa Platform.");
        builder.AppendLine("// Use this as a review aid; docker-compose.yml and config.json are the deployable artifacts.");
        builder.AppendLine();
        builder.AppendLine("var builder = WebApplication.CreateBuilder(args);");
        foreach (var package in context.Packages)
        {
            foreach (var feature in package.SelectedFeatures.Order(StringComparer.OrdinalIgnoreCase))
                builder.AppendLine($"// Enable feature: {feature} ({package.PackageId} {package.Version})");
        }

        builder.AppendLine("var app = builder.Build();");
        builder.AppendLine("app.Run();");

        return new BundleFile("Program.Generated.cs", "csharp", "text/x-csharp", false, builder.ToString());
    }
}
