<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\ValenceControl.Healing.Abstractions\ValenceControl.Healing.Abstractions.csproj" />
    <ProjectReference Include="..\ValenceControl.Healing.Core\ValenceControl.Healing.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Elsa.Diagnostics.OpenTelemetry" />
    <PackageReference Include="Elsa.Diagnostics.OpenTelemetry.Core" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>
</Project>
