// <auto-generated />
using System;
using Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa.Platform.PackageCatalog.Persistence.SqliteMigrations.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260524234110_AddWorkspaceDeployments")]
    partial class AddWorkspaceDeployments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Accounts.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique();

                    b.ToTable("ExternalIdentities");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Accounts.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SoftDeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Accounts.WorkspaceEntitlementSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanCreateCustomSources")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxPackagesIndexed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSources")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxSyncsPerDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxVersionsPerPackage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PrivateFeedsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SyncedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId")
                        .IsUnique();

                    b.ToTable("WorkspaceEntitlementSnapshots");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Accounts.WorkspaceMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("WorkspaceId", "AccountId")
                        .IsUnique();

                    b.ToTable("WorkspaceMemberships");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Manifests.FeatureRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Advanced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConflictsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DependenciesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Experimental")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtensionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("InfrastructureJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PackageVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredCapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageVersionId", "FeatureId")
                        .IsUnique();

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Manifests.FeatureSettingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClrType")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValueJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentVariable")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtensionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FeatureRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Required")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RestartRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Secret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UiJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeatureRecordId", "Name")
                        .IsUnique();

                    b.ToTable("FeatureSettings");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Packages.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Approved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestVersion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Listed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "PackageId")
                        .IsUnique();

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Packages.PackageSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ApprovalPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Browseable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExcludePatterns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IncludePatterns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSuccessfulSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerWorkspaceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PollingInterval")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SoftDeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionDiscoveryPolicy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("OwnerWorkspaceId");

                    b.ToTable("PackageSources");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Packages.PackageVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("IndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsListed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManifestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NuspecJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaVersion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SuspiciousChangeDetected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspiciousManifestHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationErrors")
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageId", "Version")
                        .IsUnique();

                    b.ToTable("PackageVersions");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Sync.ApprovalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ApprovalRecords");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Sync.ManifestValidationResultRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PackageVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaVersion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ValidatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidatorVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageVersionId");

                    b.ToTable("ManifestValidationResults");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Sync.SyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummaryCountersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Trigger")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncRuns");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Sync.SyncRunItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PackageVersionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SyncRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageVersionId");

                    b.HasIndex("SyncRunId");

                    b.ToTable("SyncRunItems");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.DeploymentApplicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique();

                    b.ToTable("DeploymentApplications");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.DeploymentEnvironmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DeployedRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeploymentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DesiredRevisionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriftStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("WorkspaceId", "ApplicationId", "Name")
                        .IsUnique();

                    b.ToTable("DeploymentEnvironments");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.DesiredStateRevisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AuthoredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Commit")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesiredStateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId", "RevisionNumber")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "ContentHash");

                    b.ToTable("DesiredStateRevisions");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.EngineCapabilityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Boundary")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EngineId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EngineId", "CapabilityId")
                        .IsUnique();

                    b.ToTable("EngineCapabilities");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.RuntimeControlEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Boundary")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EngineId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredCapabilityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EngineId", "ControlId")
                        .IsUnique();

                    b.ToTable("RuntimeControls");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.WorkflowEngineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CredentialLastVerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialProvider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialReference")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialVerificationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("HostingProvider")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("WorkspaceId", "EnvironmentId", "Name")
                        .IsUnique();

                    b.ToTable("WorkflowEngines");
                });

            modelBuilder.Entity("Elsa.Platform.RuntimeBuilder.Abstractions.RuntimeConfigurations.RuntimeConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("IntentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SoftDeletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "SoftDeletedAt");

                    b.ToTable("RuntimeConfigurations");
                });

            modelBuilder.Entity("Elsa.Platform.RuntimeBuilder.Abstractions.RuntimeConfigurations.RuntimeConfigurationVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("IntentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RuntimeConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RuntimeConfigurationId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("RuntimeConfigurationVersions");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Accounts.ExternalIdentity", b =>
                {
                    b.HasOne("Elsa.Platform.PackageCatalog.Core.Accounts.Account", "Account")
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Accounts.WorkspaceEntitlementSnapshot", b =>
                {
                    b.HasOne("Elsa.Platform.PackageCatalog.Core.Accounts.Workspace", "Workspace")
                        .WithMany("EntitlementSnapshots")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Accounts.WorkspaceMembership", b =>
                {
                    b.HasOne("Elsa.Platform.PackageCatalog.Core.Accounts.Account", "Account")
                        .WithMany("Memberships")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elsa.Platform.PackageCatalog.Core.Accounts.Workspace", "Workspace")
                        .WithMany("Memberships")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Manifests.FeatureRecord", b =>
                {
                    b.HasOne("Elsa.Platform.PackageCatalog.Core.Packages.PackageVersion", "PackageVersion")
                        .WithMany("Features")
                        .HasForeignKey("PackageVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageVersion");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Manifests.FeatureSettingRecord", b =>
                {
                    b.HasOne("Elsa.Platform.PackageCatalog.Core.Manifests.FeatureRecord", "FeatureRecord")
                        .WithMany("Settings")
                        .HasForeignKey("FeatureRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureRecord");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Packages.Package", b =>
                {
                    b.HasOne("Elsa.Platform.PackageCatalog.Core.Packages.PackageSource", "Source")
                        .WithMany("Packages")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Packages.PackageSource", b =>
                {
                    b.HasOne("Elsa.Platform.PackageCatalog.Core.Accounts.Workspace", "OwnerWorkspace")
                        .WithMany()
                        .HasForeignKey("OwnerWorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OwnerWorkspace");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Packages.PackageVersion", b =>
                {
                    b.HasOne("Elsa.Platform.PackageCatalog.Core.Packages.Package", "Package")
                        .WithMany("Versions")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Sync.ManifestValidationResultRecord", b =>
                {
                    b.HasOne("Elsa.Platform.PackageCatalog.Core.Packages.PackageVersion", "PackageVersion")
                        .WithMany()
                        .HasForeignKey("PackageVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageVersion");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Sync.SyncRunItem", b =>
                {
                    b.HasOne("Elsa.Platform.PackageCatalog.Core.Packages.PackageVersion", "PackageVersion")
                        .WithMany()
                        .HasForeignKey("PackageVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Elsa.Platform.PackageCatalog.Core.Sync.SyncRun", "SyncRun")
                        .WithMany("Items")
                        .HasForeignKey("SyncRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageVersion");

                    b.Navigation("SyncRun");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.DeploymentApplicationEntity", b =>
                {
                    b.HasOne("Elsa.Platform.PackageCatalog.Core.Accounts.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.DeploymentEnvironmentEntity", b =>
                {
                    b.HasOne("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.DeploymentApplicationEntity", "Application")
                        .WithMany("Environments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.DesiredStateRevisionEntity", b =>
                {
                    b.HasOne("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.DeploymentEnvironmentEntity", "Environment")
                        .WithMany("Revisions")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.EngineCapabilityEntity", b =>
                {
                    b.HasOne("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.WorkflowEngineEntity", "Engine")
                        .WithMany("Capabilities")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engine");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.RuntimeControlEntity", b =>
                {
                    b.HasOne("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.WorkflowEngineEntity", "Engine")
                        .WithMany("Controls")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engine");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.WorkflowEngineEntity", b =>
                {
                    b.HasOne("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.DeploymentEnvironmentEntity", "Environment")
                        .WithMany("Engines")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("Elsa.Platform.RuntimeBuilder.Abstractions.RuntimeConfigurations.RuntimeConfiguration", b =>
                {
                    b.HasOne("Elsa.Platform.PackageCatalog.Core.Accounts.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Elsa.Platform.RuntimeBuilder.Abstractions.RuntimeConfigurations.RuntimeConfigurationVersion", b =>
                {
                    b.HasOne("Elsa.Platform.RuntimeBuilder.Abstractions.RuntimeConfigurations.RuntimeConfiguration", "RuntimeConfiguration")
                        .WithMany("Versions")
                        .HasForeignKey("RuntimeConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RuntimeConfiguration");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Accounts.Account", b =>
                {
                    b.Navigation("ExternalIdentities");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Accounts.Workspace", b =>
                {
                    b.Navigation("EntitlementSnapshots");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Manifests.FeatureRecord", b =>
                {
                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Packages.Package", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Packages.PackageSource", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Packages.PackageVersion", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Core.Sync.SyncRun", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.DeploymentApplicationEntity", b =>
                {
                    b.Navigation("Environments");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.DeploymentEnvironmentEntity", b =>
                {
                    b.Navigation("Engines");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Elsa.Platform.PackageCatalog.Persistence.EntityFrameworkCore.Models.WorkflowEngineEntity", b =>
                {
                    b.Navigation("Capabilities");

                    b.Navigation("Controls");
                });

            modelBuilder.Entity("Elsa.Platform.RuntimeBuilder.Abstractions.RuntimeConfigurations.RuntimeConfiguration", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
