<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\Elsa.PackageManifests\Elsa.PackageManifests.csproj" />
    <ProjectReference Include="..\Elsa.Catalog.Core\Elsa.Catalog.Core.csproj" />
    <ProjectReference Include="..\Elsa.Catalog.Persistence.EntityFrameworkCore\Elsa.Catalog.Persistence.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\Elsa.Catalog.Persistence.SqliteMigrations\Elsa.Catalog.Persistence.SqliteMigrations.csproj" />
    <ProjectReference Include="..\Elsa.Catalog.Persistence.SqlServerMigrations\Elsa.Catalog.Persistence.SqlServerMigrations.csproj" />
    <ProjectReference Include="..\Elsa.Catalog.Packaging.NuGet\Elsa.Catalog.Packaging.NuGet.csproj" />
    <ProjectReference Include="..\Elsa.Catalog.ServiceDefaults\Elsa.Catalog.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>
</Project>
