<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Elsa.Platform.Api\Elsa.Platform.Api.csproj" />
    <ProjectReference Include="..\..\src\Elsa.Platform.PackageCatalog.Core\Elsa.Platform.PackageCatalog.Core.csproj" />
    <ProjectReference Include="..\..\src\Elsa.Platform.Studio.Submit\Elsa.Platform.Studio.Submit.csproj" />
    <ProjectReference Include="..\..\src\Elsa.Platform.Workflows.RuntimeApplier\Elsa.Platform.Workflows.RuntimeApplier.csproj" />
    <ProjectReference Include="..\Elsa.Platform.PackageCatalog.Testing\Elsa.Platform.PackageCatalog.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
