<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\ElsaControl.PackageCatalog.Core\ElsaControl.PackageCatalog.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Elsa.Specifications.PackageManifests" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="NuGet.Protocol" />
  </ItemGroup>
</Project>
